version: "3"
services:
  web:
    build:
      context: ./ubuntu-apache
    ports: 
      - 80:80
    privileged: true
    tty: true
    # links:
    #   - db
    # volumes:
    #   - "../nbsoft-post/:/var/www/html/"
    #   - "./apache-php/httpd.conf:/etc/httpd/conf/httpd.conf"
    #   - "./apache-php/php.ini:/etc/php.ini"
    #   - "./apache-php/15-xdebug.ini:/etc/php.d/15-xdebug.ini"
    container_name: "ubuntu-apache"
  # db:
  #   image: mysql:5.7
  #   ports:
  #     - 3306:3306
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=root
  #   container_name: "mysql5.7"