version: "3"
services:
  web:
    build:
      context: ./apache-php
    ports: 
      - 80:80
    privileged: true
    links:
      - db
    volumes:
      - "../nbsoft-post/:/var/www/html/"
      - "./apache-php/httpd.conf:/etc/httpd/conf/httpd.conf"
      - "./apache-php/php.ini:/etc/php.ini"
    container_name: "apache-php"
  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
    container_name: "mysql5.7"