version: "3"
services:
  web:
    build:
      context: ./centos-java-gradle
    ports: 
      - 8888:80
    tty: true
    stdin_open: true
    privileged: true
#    links:
#      - db
    volumes:
      - "../demo/:/home/in2020/springboot-init/"
      - "./centos-java-gradle/set_path.sh:/etc/profile.d/set_path.sh"
    container_name: "centos-java-gradle"
#  db:
#    image: mysql:5.7
#    environment:
#      - MYSQL_ROOT_PASSWORD=root
#    container_name: "mysql5.7"